import { Component, OnInit, AfterViewChecked, SecurityContext, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { HttpClient } from '@angular/common/http';
import { catchError } from 'rxjs/operators';
import { of } from 'rxjs';

declare var marked: any;
declare var mermaid: any;

@Component({
  selector: 'app-documentation',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './documentation.component.html',
  styleUrls: ['./documentation.component.css']
})
export class DocumentationComponent implements OnInit, AfterViewChecked {
  
  renderedHtml!: SafeHtml;
  topicTitle: string = 'Documentation';
  isLoading: boolean = true;
  private needMermaidInit = false;

  constructor(
    private route: ActivatedRoute,
    private sanitizer: DomSanitizer,
    private elRef: ElementRef,
    private http: HttpClient
  ) {}

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      this.isLoading = true;
      const topic = params['topic'] || 'default';
      this.topicTitle = (topic.charAt(0).toUpperCase() + topic.slice(1)).replace('-', ' ');
      
      const filePath = `assets/docs/${topic}.md`;

      this.http.get(filePath, { responseType: 'text' })
        .pipe(
          catchError(err => of(`# Error Loading Document\n\nThe requested technical specification (${topic}) could not be loaded dynamically from ${filePath}. Ensure the Markdown file exists and the server allows static asset retrieval.`))
        )
        .subscribe(rawMarkdown => {
          if (typeof marked !== 'undefined') {
            const parsedHtml = marked.parse(rawMarkdown);
            this.renderedHtml = this.sanitizer.bypassSecurityTrustHtml(parsedHtml);
            this.needMermaidInit = true;
          } else {
            this.renderedHtml = this.sanitizer.bypassSecurityTrustHtml('<p>Failed to load markdown parser.</p>');
          }
          this.isLoading = false;
        });
    });
  }

  ngAfterViewChecked() {
    if (this.needMermaidInit && !this.isLoading && typeof mermaid !== 'undefined') {
      try {
        // Find language-mermaid blocks generated by marked
        const mermaidNodes = this.elRef.nativeElement.querySelectorAll('code.language-mermaid');
        mermaidNodes.forEach((node: HTMLElement) => {
          // Convert code blocks into mermaid divs so mermaid.js picks them up
          const parentPre = node.parentElement;
          if (parentPre && parentPre.tagName === 'PRE') {
            const div = document.createElement('div');
            div.className = 'mermaid';
            div.textContent = node.textContent;
            parentPre.replaceWith(div);
          }
        });
        
        const mermaidElements = document.querySelectorAll('.mermaid');
        if (mermaidElements.length > 0) {
           mermaid.init(undefined, mermaidElements);
        }
        
        this.needMermaidInit = false;
      } catch(e) {
        console.error('Mermaid init error:', e);
      }
    }
  }
}
