import { Component, OnInit, AfterViewChecked, SecurityContext, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { DOCUMENTATION_DATA } from './documentation.data';

declare var marked: any;
declare var mermaid: any;

@Component({
  selector: 'app-documentation',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './documentation.component.html',
  styleUrls: ['./documentation.component.css']
})
export class DocumentationComponent implements OnInit, AfterViewChecked {
  
  renderedHtml!: SafeHtml;
  topicTitle: string = 'Documentation';
  private needMermaidInit = false;

  constructor(
    private route: ActivatedRoute,
    private sanitizer: DomSanitizer,
    private elRef: ElementRef
  ) {}

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      const topic = params['topic'] || 'default';
      this.topicTitle = (topic.charAt(0).toUpperCase() + topic.slice(1)).replace('-', ' ');
      
      const rawMarkdown = DOCUMENTATION_DATA[topic] || DOCUMENTATION_DATA['default'];
      
      if (typeof marked !== 'undefined') {
        const parsedHtml = marked.parse(rawMarkdown);
        // We use bypassSecurityTrustHtml because Markdown often generates safe layout HTML
        // Note: For public UGC, you must sanitize, but here it's static developer docs.
        this.renderedHtml = this.sanitizer.bypassSecurityTrustHtml(parsedHtml);
        this.needMermaidInit = true;
      } else {
        this.renderedHtml = this.sanitizer.bypassSecurityTrustHtml('<p>Failed to load markdown parser.</p>');
      }
    });
  }

  ngAfterViewChecked() {
    if (this.needMermaidInit && typeof mermaid !== 'undefined') {
      try {
        // Find language-mermaid blocks generated by marked
        const mermaidNodes = this.elRef.nativeElement.querySelectorAll('code.language-mermaid');
        mermaidNodes.forEach((node: HTMLElement) => {
          // Convert code blocks into mermaid divs so mermaid.js picks them up
          const parentPre = node.parentElement;
          if (parentPre && parentPre.tagName === 'PRE') {
            const div = document.createElement('div');
            div.className = 'mermaid';
            div.textContent = node.textContent;
            parentPre.replaceWith(div);
          }
        });
        mermaid.init(undefined, document.querySelectorAll('.mermaid'));
        this.needMermaidInit = false;
      } catch(e) {
        console.error('Mermaid init error:', e);
      }
    }
  }
}
